# Site settings
title: Temu Kangen 10 Tahun IKA Smansa 2005
email: me@novrian.info
description: >
  Media informasi acara Temu Kangen 10 Tahun IKA Smansa Makassar 2005
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: smansa2005
github_username:  jekyll

# Build settings
markdown: kramdown

# SASS Settings
sass:
  style: :compressed
