# Site settings
title: Temu Kangen 10 Tahun IKA Smansa 2005
email: me@novrian.info
description: >
  Media informasi acara Temu Kangen 10 Tahun IKA Smansa Makassar 2005
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://smansa2005.org" # the base hostname & protocol for your site
twitter_username: smansa2005
github_username:  jekyll
google_analytics: UA-65522870-1
gmap_API_key: "AIzaSyCyIrBEmqOb3Onm0pWmKAWtEeKmIwWngV0"
paginate: 5
line_invite_url: "http://line.me/ti/g/fKLYi6eM3R"

# Build settings
markdown: kramdown

# SASS Settings
# sass:
#   style: :compressed

gems:
  - jekyll-compass
